---
users:

  'plone':
    name: 'Plone installation'
    email: 'marfebr@gmail.com'
    public_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoxrYnG/G5DRORhFfMCFhydmeMC6vnbcqXvslGp+SoeRfRsMFOB9RMYyYVTDQ0h4ZREbnLw+rbR88ILQATVlHL218WaRQa+1p8siF3qnic5INM0uIbhfpcs5i+SykqDbpO8spFAQY7XdbTUXvm8CpxWuq7/g9n0mSyEYPyNUaGv/9zt1YDMcRf7lSqPgVCLU6iTBOvUhjn2Mk62af0U9Qls2DP1LgXFcofoG6l7f0VmFAPiSl7Rz3bEG1PNt9ayASWausH5gfKtSZgULWW3kbAhX3zUYonRzGPeavZ4aUpI18+uWojTVGDQ+Pw343T873cl7582s/F5GmkbY4IeLZx aislan@aislan-Inspiron-7559'
    password: '$6$8TrTq/2twy7u./bS$5gxT7m93.aVJD1P9V0y.EMcCvgH2RV8pM4vVyGFpqx3zEPUvmib7nQtJD6vxJRTMyR9oPRi323tbwpx0wLyWs.'
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
